import { Agent, RecentSale, Review } from '@/types';

export const mockAgents: Agent[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@realty.com',
    phone: '3105551234',
    photo_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    brokerage: 'ClearPath Realty',
    commission_rate: 1.5,
    years_experience: 12,
    total_sales: 156,
    avg_days_on_market: 28,
    rating: 4.9,
    review_count: 89,
    bio: 'Listing-focused agent specializing in luxury homes, relocation, and first-time sellers.',
    specialties: ['Residential', 'Luxury', 'First-Time Sellers', 'Relocation'],
    languages: ['English', 'Spanish'],
    license_number: 'CA-DRE-01234567',
    office_address: '123 Main St, Los Angeles, CA 90001',
    latitude: 34.0522,
    longitude: -118.2437,
    area_served: 'Los Angeles County',
    city: 'Los Angeles',
    state: 'CA',
    zip_codes: ['90001', '90012', '90015', '90026', '90046'],
    neighborhoods: ['Downtown Los Angeles', 'Echo Park', 'Silver Lake', 'Hollywood Hills'],
    service_radius_miles: 18,
    verified: true,
    accepts_referrals: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'michael.chen@realty.com',
    phone: '3105555678',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    brokerage: 'Harbor & Hill',
    commission_rate: 2.0,
    years_experience: 8,
    total_sales: 92,
    avg_days_on_market: 32,
    rating: 4.7,
    review_count: 56,
    bio: 'Investor-friendly agent with a strong record in condos, multifamily, and commercial deals.',
    specialties: ['Investment', 'Commercial', 'Condos', 'Multifamily'],
    languages: ['English', 'Mandarin'],
    license_number: 'CA-DRE-02345678',
    office_address: '456 Oak Ave, Los Angeles, CA 90002',
    latitude: 34.0622,
    longitude: -118.2537,
    area_served: 'Central Los Angeles',
    city: 'Los Angeles',
    state: 'CA',
    zip_codes: ['90002', '90007', '90011', '90037'],
    neighborhoods: ['South Park', 'University Park', 'Exposition Park'],
    service_radius_miles: 15,
    verified: true,
    accepts_referrals: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Priya Patel',
    email: 'priya.patel@westsidehomes.com',
    phone: '4245550198',
    photo_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    brokerage: 'Westside Homes',
    commission_rate: 1.75,
    years_experience: 10,
    total_sales: 131,
    avg_days_on_market: 24,
    rating: 4.8,
    review_count: 73,
    bio: 'Westside specialist for move-up buyers, coastal sellers, and competitive listing prep.',
    specialties: ['Residential', 'Luxury', 'Move-Up Buyers', 'Staging'],
    languages: ['English', 'Hindi', 'Gujarati'],
    license_number: 'CA-DRE-03456789',
    office_address: '89 Ocean Park Blvd, Santa Monica, CA 90405',
    latitude: 34.0195,
    longitude: -118.4912,
    area_served: 'Santa Monica and West LA',
    city: 'Santa Monica',
    state: 'CA',
    zip_codes: ['90401', '90403', '90405', '90025', '90064'],
    neighborhoods: ['Ocean Park', 'Sawtelle', 'Brentwood', 'West LA'],
    service_radius_miles: 12,
    verified: true,
    accepts_referrals: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Diego Ramirez',
    email: 'diego@valleylisting.com',
    phone: '8185557421',
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    brokerage: 'Valley Listing Co.',
    commission_rate: 1.25,
    years_experience: 6,
    total_sales: 68,
    avg_days_on_market: 30,
    rating: 4.6,
    review_count: 41,
    bio: 'Cost-conscious listing partner for San Fernando Valley homeowners and probate sellers.',
    specialties: ['Residential', 'Probate', 'First-Time Sellers', 'Townhomes'],
    languages: ['English', 'Spanish'],
    license_number: 'CA-DRE-04567890',
    office_address: '14420 Ventura Blvd, Sherman Oaks, CA 91423',
    latitude: 34.1511,
    longitude: -118.4493,
    area_served: 'San Fernando Valley',
    city: 'Sherman Oaks',
    state: 'CA',
    zip_codes: ['91403', '91423', '91604', '91316', '91356'],
    neighborhoods: ['Sherman Oaks', 'Studio City', 'Encino', 'Tarzana'],
    service_radius_miles: 20,
    verified: false,
    accepts_referrals: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Avery Thompson',
    email: 'avery@pasadenaporch.com',
    phone: '6265553344',
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
    brokerage: 'Pasadena Porch Realty',
    commission_rate: 2.25,
    years_experience: 15,
    total_sales: 204,
    avg_days_on_market: 21,
    rating: 5,
    review_count: 112,
    bio: 'Historic home and trust sale expert with deep roots across Pasadena and the Foothills.',
    specialties: ['Historic Homes', 'Trust Sales', 'Residential', 'Luxury'],
    languages: ['English', 'French'],
    license_number: 'CA-DRE-05678901',
    office_address: '301 Colorado Blvd, Pasadena, CA 91101',
    latitude: 34.1478,
    longitude: -118.1445,
    area_served: 'Pasadena and Foothills',
    city: 'Pasadena',
    state: 'CA',
    zip_codes: ['91101', '91103', '91105', '91001', '91011'],
    neighborhoods: ['Old Pasadena', 'South Pasadena', 'Altadena', 'La Canada Flintridge'],
    service_radius_miles: 16,
    verified: true,
    accepts_referrals: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Jordan Ellis',
    email: 'jordan.ellis@beachcitybrokers.com',
    phone: '3105558152',
    photo_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400',
    brokerage: 'Beach City Brokers',
    commission_rate: 1.9,
    years_experience: 9,
    total_sales: 118,
    avg_days_on_market: 27,
    rating: 4.8,
    review_count: 64,
    bio: 'South Bay agent for coastal listings, relocation buyers, and lease-to-sale transitions.',
    specialties: ['Coastal', 'Relocation', 'Residential', 'Condos'],
    languages: ['English', 'Korean'],
    license_number: 'CA-DRE-06789012',
    office_address: '215 Pier Ave, Hermosa Beach, CA 90254',
    latitude: 33.8622,
    longitude: -118.3995,
    area_served: 'South Bay',
    city: 'Hermosa Beach',
    state: 'CA',
    zip_codes: ['90254', '90266', '90277', '90503', '90278'],
    neighborhoods: ['Hermosa Beach', 'Manhattan Beach', 'Redondo Beach', 'Torrance'],
    service_radius_miles: 14,
    verified: true,
    accepts_referrals: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockReviews: Review[] = [
  {
    id: '1',
    agent_id: '1',
    reviewer_name: 'John Smith',
    rating: 5,
    comment: 'Clear pricing, sharp listing prep, and a faster sale than we expected.',
    property_type: 'Single Family Home',
    transaction_type: 'sell',
    created_at: '2025-11-15T00:00:00Z',
  },
  {
    id: '2',
    agent_id: '1',
    reviewer_name: 'Maria Garcia',
    rating: 5,
    comment: 'Professional, direct, and very transparent about the commission math.',
    property_type: 'Condo',
    transaction_type: 'buy',
    created_at: '2025-10-28T00:00:00Z',
  },
];

export const mockRecentSales: RecentSale[] = [
  {
    id: '1',
    agent_id: '1',
    address: '456 Ocean Ave',
    city: 'Santa Monica',
    state: 'CA',
    zip_code: '90401',
    price: 2850000,
    property_type: 'Single Family Home',
    bedrooms: 4,
    bathrooms: 3,
    square_feet: 2800,
    sold_date: '2025-11-20',
    days_on_market: 22,
    image_url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400',
  },
  {
    id: '2',
    agent_id: '1',
    address: '789 Beverly Dr',
    city: 'Beverly Hills',
    state: 'CA',
    zip_code: '90210',
    price: 4500000,
    property_type: 'Luxury Home',
    bedrooms: 5,
    bathrooms: 5,
    square_feet: 4200,
    sold_date: '2025-10-15',
    days_on_market: 31,
    image_url: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=400',
  },
];
